function WRITE_TABLE_TEX(filename, statistics)
%WRITE_TABLE_TEX Export a booktabs table fragment for baseline or comparison results.
fid = fopen(filename,'w','n','UTF-8'); % Write portable UTF-8 LaTeX source.
if fid < 0, error('ABSJ2027:Export','Could not open %s for writing.',filename); end % Report an unwritable destination.
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU> % Close the file even if export fails.
comparison = ismember('Counterfactual',statistics.Properties.VariableNames); % Select columns from the actual table.
fprintf(fid,'%% Generated by ABSJ2027; requires \\usepackage{booktabs}.\n'); % Document the only extra LaTeX package.
fprintf(fid,'\\begin{table}[htbp]\n\\centering\n\\caption{City equilibrium statistics}\n\\small\n'); % Follow the academic codebook table style.
if comparison
    fprintf(fid,'\\begin{tabular}{p{3.9cm}p{2.7cm}rrr}\n\\toprule\nMetric & Unit & Baseline & Counterfactual & Change (\\%%) \\\\\n'); % Label percentage changes explicitly.
else
    fprintf(fid,'\\begin{tabular}{p{4.5cm}p{3.2cm}r}\n\\toprule\nMetric & Unit & Baseline \\\\\n'); % Omit unused columns in baseline-only mode.
end
fprintf(fid,'\\midrule\n'); % Separate column labels and observations.
for row = 1:height(statistics)
    fprintf(fid,'%s & %s',TEX_ESCAPE(statistics.Metric(row)),TEX_ESCAPE(statistics.Unit(row))); % Escape user-facing labels.
    for col = 3:width(statistics)
        value = statistics{row,col}; % Extract numeric levels or percentage changes.
        if isnan(value)
            formatted = '--'; % Undefined percentage changes are not zero.
        elseif isinf(value)
            if value > 0, formatted = '$\infty$'; else, formatted = '$-\infty$'; end % Typeset unbounded values.
        else
            formatted = sprintf('%.6g',value); % Keep the printed table compact; CSV/XLSX retain numeric precision.
        end
        fprintf(fid,' & %s',formatted); % Append a numeric column without changing the stored table.
    end
    fprintf(fid,' \\\\\n'); % Finish the LaTeX row.
end
fprintf(fid,'\\bottomrule\n\\end{tabular}\n'); % Close the ruled table.
fprintf(fid,'\\par\\smallskip\\begin{minipage}{0.96\\linewidth}\\footnotesize\n'); % Keep the note within the page width.
fprintf(fid,'Notes: Monetary units and periods are given in the Unit column; rents are per square metre. Commuting disamenity income losses are utility equivalents. Height gap uses each scenario without height limits as benchmark at T; it is descriptive under empirical parameters. -- denotes an undefined value, including a gap with no unrestricted tall development. '); % State the unit convention.
if comparison, fprintf(fid,'Changes are percentages relative to the baseline; -- denotes an undefined comparison. '); end % Explain comparison-only notation.
fprintf(fid,'Displayed values are rounded to six significant digits; CSV and Excel files retain numeric values.\n'); % Distinguish print precision from data precision.
fprintf(fid,'\\end{minipage}\n\\end{table}\n'); % Finish the includable fragment.
end
