const worker = new Worker('simulator-worker.js');
const $ = id => document.getElementById(id);
let started = 0;
const value = id => { const raw=$(id).value.trim(); return raw===''?null:Number(raw); };
function payload(){return {baseline:{population:value('population'),urbanization_rate:value('urbanization')/100},changes:{pct:{a_bar_C:value('prod-c'),a_bar_R:value('amen-r'),c_C:value('cost-c'),c_R:value('cost-r'),tau_C:value('tau-c'),tau_R:value('tau-r')},set:{S_bar_C:value('cap-c'),S_bar_R:value('cap-r'),x1_max:value('boundary')}}};}
function format(value,digits=2){return value==null?'—':Number(value).toLocaleString('en',{maximumFractionDigits:digits});}
function percent(value){return value==null?'—':`${value>=0?'+':'−'}${format(Math.abs(value)*100,2)}%`;}
const metrics=[['N','Population',0],['y','Wage',3],['GDP','GDP',2],['p_R','Residential rent',3],['LV','Aggregate land rent',2],['AREA','Urban area',2],['CC','Commuting disamenity',3],['density','Density',2],['V','Expected utility',4]];
function cards(result){$('cards').replaceChildren(...metrics.map(([key,label,digits])=>{const el=document.createElement('div');el.className='card';el.innerHTML=`<span>${label}</span><strong>${format(result.counterfactual.aggregates[key],digits)}</strong><em>${percent(result.changes[key])} from baseline</em>`;return el;}));}
function svg(tag,attributes,text){const el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,val] of Object.entries(attributes))el.setAttribute(key,val);if(text!=null)el.textContent=text;return el;}
const seriesConfig={height:[['commercial_height','#205b83'],['residential_height','#65a3c7']],floor_rent:[['commercial_floor_rent','#205b83'],['residential_floor_rent','#65a3c7']],land_rent:[['commercial_land_rent','#205b83'],['residential_land_rent','#65a3c7'],['agricultural_land_rent','#777']]};
function spatialChart(title,base,counter,kind){const width=520,height=250,left=52,right=14,top=14,bottom=48,strip=14;const plotBottom=height-bottom-strip;const all=[...seriesConfig[kind].flatMap(([name])=>[...base[name],...counter[name]])].filter(Number.isFinite);const ymax=Math.max(...all,1);const xmax=Math.max(...base.distance,...counter.distance);const x=v=>left+v/xmax*(width-left-right),y=v=>plotBottom-v/ymax*(plotBottom-top);const root=svg('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':title});
 for(let i=0;i<=4;i++){const yy=top+(plotBottom-top)*i/4;root.append(svg('line',{x1:left,x2:width-right,y1:yy,y2:yy,stroke:'#ddd','stroke-dasharray':'2 3'}));root.append(svg('text',{x:left-7,y:yy+4,'text-anchor':'end','font-size':10},format(ymax*(1-i/4),2)));}
 for(let i=0;i<=5;i++){const xx=left+(width-left-right)*i/5;root.append(svg('line',{x1:xx,x2:xx,y1:top,y2:plotBottom,stroke:'#eee','stroke-dasharray':'2 3'}));root.append(svg('text',{x:xx,y:height-5,'text-anchor':'middle','font-size':10},format(xmax*i/5,1)));}
 function path(profile,name){let d='',open=false;profile.distance.forEach((distance,i)=>{const v=profile[name][i];if(Number.isFinite(v)){d+=`${open?'L':'M'}${x(distance)},${y(v)}`;open=true;}else open=false;});return d;}
 [['baseline',base,''],['counterfactual',counter,'6 3']].forEach(([scenario,profile,dash])=>seriesConfig[kind].forEach(([name,color])=>root.append(svg('path',{d:path(profile,name),fill:'none',stroke:scenario==='baseline'?color:'#a45c1c','stroke-width':scenario==='baseline'?2:2.4,'stroke-dasharray':dash,opacity:name.startsWith('residential')?.72:1}))));
 const useColors={1:'#205b83',2:'#65a3c7',3:'#b9b9b9'};[[base,plotBottom+3],[counter,plotBottom+10]].forEach(([profile,yy])=>profile.distance.slice(0,-1).forEach((distance,i)=>root.append(svg('rect',{x:x(distance),y:yy,width:Math.max(1,x(profile.distance[i+1])-x(distance)+.3),height:6,fill:useColors[profile.land_use[i]]||'#fff'}))));
 root.append(svg('text',{x:(left+width-right)/2,y:height-20,'text-anchor':'middle','font-size':11},'Distance from CBD (model units)'));return root;}
function chartPanel(title,node){const el=document.createElement('div');el.className='chart';const h=document.createElement('h3');h.textContent=title;el.append(h,node);return el;}
function changeChart(result){const selected=metrics.map(([key,label])=>[label,result.changes[key]]);const max=Math.max(.01,...selected.map(([,v])=>Math.abs(v||0)));const width=520,height=250,left=145,right=55,top=10,row=24;const root=svg('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':'Aggregate percentage changes'}),zero=left+(width-left-right)/2,scale=(width-left-right)/2/max;selected.forEach(([label,v],i)=>{const yy=top+i*row;root.append(svg('text',{x:left-7,y:yy+14,'text-anchor':'end','font-size':10},label));root.append(svg('line',{x1:left,x2:width-right,y1:yy+9,y2:yy+9,stroke:'#eee'}));if(v!=null)root.append(svg('rect',{x:v<0?zero+v*scale:zero,y:yy,width:Math.abs(v)*scale,height:17,fill:v<0?'#a45c1c':'#205b83'}));root.append(svg('text',{x:width-right+5,y:yy+13,'font-size':10},percent(v)));});root.append(svg('line',{x1:zero,x2:zero,y1:top,y2:top+selected.length*row,stroke:'#777'}));return root;}
function render(result){cards(result);const b=result.baseline.profile,c=result.counterfactual.profile;$('charts').replaceChildren(chartPanel('Building height / FAR',spatialChart('Building height or FAR',b,c,'height')),chartPanel('Floor-space rent',spatialChart('Floor-space rent',b,c,'floor_rent')),chartPanel('Land rent',spatialChart('Land rent',b,c,'land_rent')),chartPanel('Aggregate changes',changeChart(result)));$('results').hidden=false;$('runtime').textContent=`Completed in ${format((performance.now()-started)/1000,1)} seconds in this browser.`;}
worker.onmessage=event=>{const message=event.data;if(message.type==='ready'){$('run').disabled=false;$('run').textContent='Run simulation';$('status').textContent='Ready. The first model calculation may take a few seconds.';}else if(message.type==='status'){$('status').textContent=message.message;}else if(message.type==='result'){render(message.result);$('run').disabled=false;$('run').textContent='Run simulation';$('status').textContent='Simulation complete.';}else if(message.type==='error'){$('run').disabled=false;$('run').textContent='Run simulation';$('status').classList.add('error');$('status').textContent=message.message;}};
$('controls').addEventListener('submit',event=>{event.preventDefault();$('status').classList.remove('error');$('run').disabled=true;$('run').textContent='Solving…';$('results').hidden=true;started=performance.now();worker.postMessage({type:'simulate',payload:payload()});});
